### ISSUE TITLE
tCNNS

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/tCNNS-Project#1]
# First iteration

SOP:

- [x] Test container build
- [x] Test train with container
- [x] Create improve branch in model repo
- [x] Switch to improve branch in image build
- [x] Test HPO
- [x] Tag improve branch with v0.6.0

# Second iteration

Started: 2023-09-27
Branch: improve

SOP:

- [x] Test container build
- [x] Test train with container
- [x] Test HPO
- [x] Update tag v0.6.1 from improve branch
- [x] Update definition file

Depends on:
- #4

**Comment by wilke** [comment]
```
 time supervisor conda GA tests/tCNNS/cfg-nightly.sh | tee tCNNS.log

mkdir: created directory '/software/improve/data_dir//tCNNS/output/tCNNS/EXP001/run'
mkdir: created directory '/software/improve/data_dir//tCNNS/output/tCNNS/EXP001/out'
/homes/wilke/miniconda3/envs/IMPROVE/bin/python
/homes/wilke/miniconda3/envs/IMPROVE/bin/swift-t
WARN  /tmp/swift-t-workflow.pEP.swift:93:8: Variable usage warning. Variable v might be read and not written, possibly leading to deadlock
WARN  model_container.swift:15:23: variable called model_name already defined at swift-t-workflow.pEP.swift:145
WARN  model_container.swift:41:14: variable called model_name already defined at swift-t-workflow.pEP.swift:145
WARN  /home/wilke/IMPROVE/Supervisor/workflows/common/ext/EQ-Py/EQPy.swift:26: Variable usage warning. Variable loc is not used
EXIT CODE: 0

real    33m58.535s
user    102m28.829s
sys     8m25.625s
```

**Comment by wilke** [comment]
Reopening - @rajeeja and @jonesse3 are updating code. Adding support for --epochs option. Need to redo tests.

**Comment by jonesse3** [comment]
Added support for --epochs option. Please rerun tests. Let me know if there's any issues.

**Comment by jonesse3** [comment]
@rajeeja @wilke improve branch has been updated

**Comment by wilke** [comment]
I got an error.  See #4

**Comment by jonesse3** [comment]
@wilke Please try again with --epochs 1.
