### ISSUE TITLE
checkpointing dir

### ISSUE THREAD

**Issue by rajeeja** [JDACS4C-IMPROVE/tCNNS-Project#2]
currently set at `ckpt_directory = '/candle_data_dir/model`

causes error 

`
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: /candle_data_dir/model/result.ckpt.data-00000-of-00001.tempstate9476190345254691315; No such file or directory
	 [[{{node save/SaveV2}}]]

`

possible fix might be setting it to  ` RUN/EXP folder`. 

Best to disable by default. #1

**Comment by jonesse3** [comment]
Modified ckpt_directory to `model` and added code to add this directory to the args.output_dir in tcnns_baseline_tensorflow.py.

**Comment by jonesse3** [comment]
Note that this change is on the develop branch.
