### ISSUE TITLE
epochs arg not working

### ISSUE THREAD

**Issue by rajeeja** [JDACS4C-IMPROVE/tCNNS-Project#3]
`
singularity exec --nv --bind /homes/jain/temp:/candle_data_dir /homes/jain/Singularity/build//tCNNS.sif train.sh 3 /candle_data_dir --learning_rate 3.1070012584004475e-05 --batch_size 1028 --epochs 5 --experiment_id EXP002 --run_id run_01_001_0001
`

--epochs 5 is not read it, it still runs for 122 epochs, possible `num_epochs` instead of `epochs`

**Comment by rajeeja** [comment]
can we add that option to run to specific number of epochs along with early stopping as the authors wrote?

We might not always want to run for all those epochs and enforce a fixed number.

**Comment by jonesse3** [comment]
I think I can add that option. I'll probably have epochs be default "None" but if there's a number it would use that. So far there are the two conditions I can incorporate. I'm not sure if there should be third condition with early stopping or not. 

1) If epochs is None, use original code for early stopping
2) If epochs is a number, run the model for that number of epochs and stop
3) If epochs is a number, run the model and do early stopping. (not sure how this would work)

**Comment by rajeeja** [comment]
Let's do option 2.
3 can come later.

**Comment by jonesse3** [comment]
Added epochs to code. 

There are three options to use epochs and early stopping (parameter is es_epochs). 

- If epochs is 0, early stopping is used
- If epochs is not 0, then the model runs for that number of epochs and stops. Early stopping can be set to 0 to not use this feature
- If epochs is a number and es_epoch is a number, model runs for the number of epochs unless model doesn't improve over x epochs (will end early).
